spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://localhost:3306/loandb
    username: root
    password: 36133520
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8004