server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: simulator-service
          uri: lb://simulator-service
          predicates:
            - Path=/simulator/**
        - id: status-service
          uri: lb://status-service
          predicates:
            - Path=/status/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
              - Path=/evaluation/**