apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service-deployment
  labels:
    app: evaluation-service-deployment
spec:
  selector:
    matchLabels:
      app: evaluation-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: evaluation-service-deployment
    spec:
      containers:
        - name: evaluation-service
          image: javieravg/evaluation-service:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service-service
  labels:
    app: evaluation-service-service
spec:
  selector:
    app: evaluation-service-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer