apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service-deployment
  labels:
    app: loan-service-deployment
spec:
  selector:
    matchLabels:
      app: loan-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: loan-service-deployment
    spec:
      containers:
        - name: loan-service
          image: javieravg/loan-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_LOANS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_LOANS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_NAME_LOANS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_USER_LOANS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_PASSWORD_LOANS
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service-service
  labels:
    app: loan-service-service
spec:
  selector:
    app: loan-service-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer