apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  DB_USER_CLIENTS: cm9vdA==
  DB_PASSWORD_CLIENTS: MzYxMzM1MjA=
  DB_USER_LOANS: cm9vdA==
  DB_PASSWORD_LOANS: MzYxMzM1MjA=
  DB_USER_STATUSES: cm9vdA==
  DB_PASSWORD_STATUSES: MzYxMzM1MjA=