apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-service-deployment
  labels:
    app: simulator-service-deployment
spec:
  selector:
    matchLabels:
      app: simulator-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: simulator-service-deployment
    spec:
      containers:
        - name: simulator-service
          image: javieravg/simulator-service:latest
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: simulator-service-service
  labels:
    app: simulator-service-service
spec:
  selector:
    app: simulator-service-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer