spring:
  application:
    name: status-service
  datasource:
    url: jdbc:mysql://localhost:3306/statusdb
    username: root
    password: 36133520
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8003
